apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: cups.coffee.coffeenetes.io
spec:
  group: coffee.coffeenetes.io
  names:
    kind: Cup
    plural: cups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            drink:
              type: string
            podSpec:
              properties:
                requests:
                  type: object
                requirements:
                  type: object
              type: object
            size:
              properties:
                maxLimit:
                  format: int64
                  type: integer
                minLimit:
                  format: int64
                  type: integer
                request:
                  format: int64
                  type: integer
              required:
              - request
              type: object
          required:
          - drink
          type: object
        status:
          properties:
            brew:
              properties:
                end:
                  format: date-time
                  type: string
                start:
                  format: date-time
                  type: string
                state:
                  type: string
              required:
              - state
              type: object
            conditions:
              items:
                properties:
                  lastProbeTime:
                    format: date-time
                    type: string
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            descriptors:
              type: object
            size:
              format: int64
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
